image: Visual Studio 2019

init:
  - git config --global core.autocrlf true
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - nuget restore src\gsudo.sln

clone_folder: c:\git\gsudo

platform: Any CPU
configuration: Release
  
build:
  parallel: true
  project: src\gsudo.sln
  verbosity: minimal
  
test:
  assemblies:
    only:
      - gsudo.Tests.dll

artifacts:
  - path: 'src\gsudo\bin'
    name: release
    
cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
