image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - nuget restore src\gsudo.sln

after_build:
  - 7z a gsudo.%CONFIGURATION%.%APPVEYOR_BUILD_VERSION%.Unsigned.zip %APPVEYOR_BUILD_FOLDER%\src\gsudo\bin\*.*
  - appveyor PushArtifact gsudo.%CONFIGURATION%.%APPVEYOR_BUILD_VERSION%.Unsigned.zip

clone_folder: c:\git\gsudo

platform: Any CPU
configuration: Release

build:
  parallel: true
  project: src\gsudo.sln
  verbosity: minimal

test:
  assemblies:
    only:
      - gsudo.Tests.dll

cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
